# Generated by Django 2.0.3 on 2018-03-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alpha',
            new_name='Listing',
        ),
    ]
