# Generated by Django 2.0.3 on 2018-03-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20180316_0417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
